(cl:defpackage exercise2-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SUMOFINTS"
   "<SUMOFINTS-REQUEST>"
   "SUMOFINTS-REQUEST"
   "<SUMOFINTS-RESPONSE>"
   "SUMOFINTS-RESPONSE"
  ))

