// Generated by gencpp from file exercise2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef EXERCISE2_MESSAGE_ADDTWOINTS_H
#define EXERCISE2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <exercise2/AddTwoIntsRequest.h>
#include <exercise2/AddTwoIntsResponse.h>


namespace exercise2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace exercise2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise2::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::exercise2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::exercise2::AddTwoInts > {
  static const char* value()
  {
    return "exercise2/AddTwoInts";
  }

  static const char* value(const ::exercise2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::exercise2::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::exercise2::AddTwoInts >
template<>
struct MD5Sum< ::exercise2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise2::AddTwoInts >::value();
  }
  static const char* value(const ::exercise2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise2::AddTwoIntsRequest> should match
// service_traits::DataType< ::exercise2::AddTwoInts >
template<>
struct DataType< ::exercise2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::exercise2::AddTwoInts >::value();
  }
  static const char* value(const ::exercise2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise2::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::exercise2::AddTwoInts >
template<>
struct MD5Sum< ::exercise2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise2::AddTwoInts >::value();
  }
  static const char* value(const ::exercise2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise2::AddTwoIntsResponse> should match
// service_traits::DataType< ::exercise2::AddTwoInts >
template<>
struct DataType< ::exercise2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::exercise2::AddTwoInts >::value();
  }
  static const char* value(const ::exercise2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE2_MESSAGE_ADDTWOINTS_H
