// Generated by gencpp from file exercise2/SumOfIntsResponse.msg
// DO NOT EDIT!


#ifndef EXERCISE2_MESSAGE_SUMOFINTSRESPONSE_H
#define EXERCISE2_MESSAGE_SUMOFINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise2
{
template <class ContainerAllocator>
struct SumOfIntsResponse_
{
  typedef SumOfIntsResponse_<ContainerAllocator> Type;

  SumOfIntsResponse_()
    : sum(0)  {
    }
  SumOfIntsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::exercise2::SumOfIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise2::SumOfIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SumOfIntsResponse_

typedef ::exercise2::SumOfIntsResponse_<std::allocator<void> > SumOfIntsResponse;

typedef boost::shared_ptr< ::exercise2::SumOfIntsResponse > SumOfIntsResponsePtr;
typedef boost::shared_ptr< ::exercise2::SumOfIntsResponse const> SumOfIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise2::SumOfIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise2::SumOfIntsResponse_<ContainerAllocator1> & lhs, const ::exercise2::SumOfIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise2::SumOfIntsResponse_<ContainerAllocator1> & lhs, const ::exercise2::SumOfIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::SumOfIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise2::SumOfIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::SumOfIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::exercise2::SumOfIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise2/SumOfIntsResponse";
  }

  static const char* value(const ::exercise2::SumOfIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
"\n"
;
  }

  static const char* value(const ::exercise2::SumOfIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumOfIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise2::SumOfIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise2::SumOfIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE2_MESSAGE_SUMOFINTSRESPONSE_H
