// Generated by gencpp from file exercise2/SumOfIntsRequest.msg
// DO NOT EDIT!


#ifndef EXERCISE2_MESSAGE_SUMOFINTSREQUEST_H
#define EXERCISE2_MESSAGE_SUMOFINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise2
{
template <class ContainerAllocator>
struct SumOfIntsRequest_
{
  typedef SumOfIntsRequest_<ContainerAllocator> Type;

  SumOfIntsRequest_()
    : a(0)  {
    }
  SumOfIntsRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::exercise2::SumOfIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise2::SumOfIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SumOfIntsRequest_

typedef ::exercise2::SumOfIntsRequest_<std::allocator<void> > SumOfIntsRequest;

typedef boost::shared_ptr< ::exercise2::SumOfIntsRequest > SumOfIntsRequestPtr;
typedef boost::shared_ptr< ::exercise2::SumOfIntsRequest const> SumOfIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise2::SumOfIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise2::SumOfIntsRequest_<ContainerAllocator1> & lhs, const ::exercise2::SumOfIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise2::SumOfIntsRequest_<ContainerAllocator1> & lhs, const ::exercise2::SumOfIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::SumOfIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise2::SumOfIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::SumOfIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "019706110004b728d56d8baaa8e32797";
  }

  static const char* value(const ::exercise2::SumOfIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x019706110004b728ULL;
  static const uint64_t static_value2 = 0xd56d8baaa8e32797ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise2/SumOfIntsRequest";
  }

  static const char* value(const ::exercise2::SumOfIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
;
  }

  static const char* value(const ::exercise2::SumOfIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumOfIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise2::SumOfIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise2::SumOfIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE2_MESSAGE_SUMOFINTSREQUEST_H
